#!/bin/sh

# scons lacks a full cleaning mechanism, as documented in
# https://github.com/SCons/scons/issues/2268

# This script exists to document as running code the proper way to
# clean all build state.

# Run the scons clean command.
scons --clean

# However, a cache file is written after cleaning.  Because the name
# varies depending on the Python pickle protocol, attempt to remove
# all possible variants.
rm -rf .sconsign.*dblite
