.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GARMINTOOL" "1" "10/08/2006" "08 Oct 2006" "08 Oct 2006"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
garmintool \- Control the modes of a Garmin GPS
.SH "SYNOPSIS"
.HP 11
\fBgarmintool\fR [\-?] [\-h] [\-n] [\-b] [\-D\ \fIdebuglevel\fR] [\-V] \fIserial\-port\fR
.SH "DESCRIPTION"
.PP
garmintool
switch a serial Garmin GPS to NMEA or Garmin Binary mode. On exit it leaves the serial port set to the proper baud rate.
.PP
This tool is not for use with Garmin USB devices. Those are permanently set to Garmin Binary mode.
.PP
You will probably need to be root to run this program, as the serial device it uses is normally privileged.
.PP
The program accepts the following options:
.TP
\-?
Display program usage and exit.
.TP
\-b
Force GPS into binary mode. After the GPS resets itself autobaud to the new speed. Binary mode is always 9600 8N1.
.TP
\-n
Force GPS into NMEA mode. After the GPS resets itself autobaud to the new speed.
.TP
\-h
Display program usage and exit.
.TP
\-D
Set debug level.
.TP
\-V
Display program version and exit.
.SH "BUGS AND LIMITATIONS"
.PP
The logic for hunting the GPS's baud rate is vulnerable to various sorts of RS232 flakiness. If it hangs for longer than a few seconds, kill the program and restart.
.SH "SEE ALSO"
.PP
\fBgpsd\fR(8),
\fBgps\fR(1),
\fBlibgps\fR(3),
\fBlibgpsd\fR(3),
\fBgpsprof\fR(1),
\fBgpsfake\fR(1),
\fBgnuplot\fR(1).
.SH "AUTHOR"
.PP
Gary E. Miller
<gem@rellim.com>. This code is part of the gpsd toolset; there is a project page for
gpsd[1]\&\fIhere\fR.
.SH "REFERENCES"
.TP 3
1.\ here
\%http://gpsd.berlios.de/
