.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GPS" "1" "10/30/2006" "9 Aug 2004" "9 Aug 2004"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
gps, xgps, xgpsspeed, cgps, cgpxlogger \- test clients for gpsd
.SH "SYNOPSIS"
.HP 5
\fBxgps\fR [\fIX\-options\fR] [\-h] [\-V] [\-speedunits\ {[mph]\ [kph]\ [knots]}] [\-altunits\ {[feet]\ [meters]}] [\-l\ [[d]\ [m]\ [s]]] [\-s\ \fIsmoothing\fR] [\fIserver\fR [\fI:port\fR [\fI:device\fR]]]
.HP 10
\fBxgpsspeed\fR [\-rv] [\fIX\-options\fR] [\-h] [\-V] [\-nc\ \fIX\-color\fR] [\-speedunits\ {[mph]\ [kph]\ [knots]}] [\fIserver\fR [\fI:port\fR [\fI:device\fR]]]
.HP 5
\fBcgps\fR [\-h] [\-s] [\-V] [\-speedunits\ {[mph]\ [kph]\ [knots]}] [\-altunits\ {[feet]\ [meters]}] [\-l\ [[d]\ [m]\ [s]]] [\fIserver\fR [\fI:port\fR [\fI:device\fR]]]
.HP 10
\fBgpxlogger\fR [\fIlogfile\fR]
.HP 11
\fBcgpxlogger\fR [\-s\ \fIgpsd\-server\fR] [\-p\ \fIgpsd\-port\fR] [\-i\ \fIpoll\-interval\fR] [\-h]
.SH "DESCRIPTION"
.SS "xgps"
.PP
xgps
is a simple test client for
gpsd
with an X interface. It displays current GPS position/time/velocity information and (for GPSes that support the feature) the locations of accessible satellites.
.PP
xgps
accepts an \-h option as for
gpsd, or a \-V option to dump the package version and exit.
.PP
An optional argument may specify a server to get data from; a colon\-separated suffix is taken as a port number. If there is a second colon\-separated suffix, that is taken as a device name to be handed to the daemon in an F= command.
.PP
The
\fB\-speedunits\fR
option can be used to set the speed units for display; follow the keyword with knots for nautical miles per hour, kph for kilometres per hour, or mph for miles per hour. The default is miles per hour. This option can also be set as the X resource 'speedunits'.
.PP
The
\fB\-altunits\fR
option can be used to set the altitude units for display; follow the keyword with 'meters' or 'feet'. The default is feet. This option can also be set as the X resource 'altunits'.
.PP
The
\fB\-l\fR
option sets the format of latitude and longitude reports. The value 'd' produces decimal degrees and is the default. The value 'm' produces degrees and decimal minutes. The value 's' produces degrees, minutes, and decimal seconds.
.PP
The
\fB\-s\fR
option sets the number of received sentences to process after any fix is received before blanking any field. By default it is set to 0, so you see each update exactly as it is sent. Setting it to a higher value prevents annoying display flicker on NMEA devices that send several difference sentence types per update cycle, only one of which is a true fix. (This option is redundant with the GPD J request and may be removed in the future.)
.PP
There is a known bug in
xgps; it assumes the default font size is no more than 18 pixels. If this is not the case, the satellite data display will show fewer than 12 satellites.
.SS "xgpsspeed"
.PP
xgpsspeed
is a speedometer that uses position information from the GPS. It accepts an \-h option and optional argument as for
gps, or a \-V option to dump the package version and exit. Additionally, it accepts \-rv (reverse video) and \-nc (needle color) options.
.PP
The \-speedunits option can be used to set the speed units for display; follow the keyword with knots for nautical miles per hour, kph for kilometres per hour, or mph for miles per hour. The default is miles per hour. This option can also be set as the X resource 'speedunits'.
.SS "cgps"
.PP
cgps
is a client resembling
xgps, but without the pictorial satellite display and able to run on a serial terminal or terminal emulator.
.PP
The
\fB\-s\fR
option prevents
cgps
from printing the raw data. This display can also be toggled with the s command.
.PP
Rather than use X resources to determine which units to use,
cgps
looks at variables in its environment. Here are the variables and values it checks:
.sp
.nf
    GPSD_UNITS one of: 
              imperial   = miles/feet
              nautical   = knots/feet
              metric     = km/meters
    LC_MEASUREMENT
	      en_US      = miles/feet
              C          = miles/feet
              POSIX      = miles/feet
              [other]    = km/meters
    LANG
	      en_US      = miles/feet
              C          = miles/feet
              POSIX      = miles/feet
              [other]    = km/meters
.fi
.PP
cgps
terminates when you send it a SIGHUP or SIGINT; given default terminal settings this will happen when you type Ctl\-C at it. It will also terminate on 'q'
.SS "cgpxlogger"
.PP
This program connects to gpsd, polls for location, and logs each fix to standard output in GPX (XML) format.
.PP
The program also writes start and end messages to syslog.
.SS "gpxlogger"
.PP
This program listens to DBUS broadcasts from gpsd (org.gpsd.fix) and logs each fix to standard output as they arrive in an XML format.
.PP
The output may be composed of multiple tracks. A new track is created if there's no fix for 5 seconds.
.PP
The program also writes start and end messages to syslog.
.SH "SEE ALSO"
.PP
\fBgpsd\fR(8),
\fBlibgps\fR(3),
\fBlibgpsd\fR(3),
\fBgpsprof\fR(1),
\fBgpsfake\fR(1).
.SH "AUTHORS"
.PP
Remco Treffcorn, Derrick Brashear, Russ Nelson & Eric S. Raymond(xgps). Jeff Francis (cgps). Amaury Jacquot
<sxpert@esitcom.org>
& Petter Reinholdtsen
<pere@hungry.com>
(gpxlogger). Chris Kuethe
<chris.kuethe@gmail.com>
(cgpxlogger).
.PP
This manual page by Eric S. Raymond
<esr@thyrsus.com>. There is a project page, with
xgps
screenshots, at
[1]\&\fIberlios.de\fR.
.SH "REFERENCES"
.TP 3
1.\ berlios.de
\%http://gpsd.berlios.de/
