#!/usr/bin/env python
#
# Collect latency-profiling data from a running gpsd.
import time, getopt, gps

if __name__ == '__main__':
    session = gps.gps(host="localhost", port="2947")

    session.query("wZ+")

    print "#GPS time          Received   Transmitted  Read"
    print "-----------------  ---------  -----------  ----------"
    while True:
        session.poll()
        gps_time = gps.isotime(session.utc)
        recv_time = session.recv_time
        emit_time = session.emit_time
        print "%.6f  %2.6f  %2.6f      %2.6f" \
              % (gps_time,
                 (recv_time - gps_time) % 3600,
                 emit_time - recv_time, time.time() - recv_time)


