#!/bin/sh
#
# putrpm -- generate RPMs from the GPSD distribution and zip them to stdout

arch={$1:`arch`}

echo "Building RPMs for $arch on $HOSTNAME." 1>&2

# Someday we may want to use arch to restrict the set of RPMs copied back.

(svn up && \
	./autogen.sh && \
	make && \
	make dist && \
	buildrpms gpsd-`make version`.tar.gz) 1>&2
zip - *`make version`*rpm


