.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "RTCMDECODE" "1" "06/06/2006" "13 Jul 2005" "13 Jul 2005"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
rtcmdecode \- decode RTCM104 streams into a readable format
.SH "SYNOPSIS"
.HP 11
\fBrtcmdecode\fR [\-d] [\-e] [\-v\ \fIdebuglevel\fR]
.SH "DESCRIPTION"
.PP
This tool is a decoder for RTCM\-104, an obscure and complicated serial protocol used for broadcasting pseudorange corrections from differential\-GPS reference stations. RTCM\-104 is expected on standard input; an equivalent, 100%\-information\-preserving text format is written to standard output.
.PP
You can use this tool with
\fBnc\fR(1)
to examine RTCM feeds from DGPSIP servers or Ntrip broadcasters.
.PP
The decoder dump format is described in
\fBrtcm\fR(5); these lines go to standard output. As well as data the decoder also prints decoder status messages to standard error, as necessary.
.SH "OPTIONS"
.PP
The \-d option tells the program to decode RTCM\-104 presented on standard input to a text dump in the format of
\fBrtcm\-104\fR(5)
on standard output. This is the default behavior.
.PP
The \-e option option tells the program to encode a text dump in the format of
\fBrtcm\-104\fR(5)
to standard output.
.PP
The \-v option sets a verbosity level. It is mainly of interest to developers.
.SH "APPLICABLE STANDARDS"
.PP
The applicable standard is
RTCM Recommended Standards for Differential NAVSTAR GPS Service
RTCM Paper 194\-93/SC 104\-STD.
.PP
Ordering instructions are accessible from the website of the
[1]\&\fIRadio Technical Commission for Maritime Services\fR
under "Publications".
.SH "BUGS AND LIMITATIONS"
.PP
RTCM\-104 represents floating\-point quantities as an integer multiple of a fixed scale factor. Editing an RTCM\-104 dump can produce numbers that are not an integer multiple of the scale factor for their field. If you do this, the value actually packed into binary RTCM\-104 will be rounded down to the nearest scale unit, and dumping will show slightly different numbers than those you entered.
.PP
The decoder logic is sufficiently convoluted to confuse some compiler optimizers, notably in GCC 3.x at \-O2, into generating bad code.
.SH "SEE ALSO"
.PP
\fBgpsd\fR(8),
\fBgps\fR(1),
\fBlibgps\fR(3),
\fBlibgpsd\fR(3),
\fBgpsprof\fR(1),
\fBgpsfake\fR(1),
\fBrtcm\-104\fR(5).
.SH "AUTHOR"
.PP
Eric S. Raymond
<esr@thyrsus.com>. This is a somewhat hacked version of an RTCM decoder originally written by Wolfgang Rupprecht. There is a project page for
gpsd[2]\&\fIhere\fR.
.SH "REFERENCES"
.TP 3
1.\ Radio Technical Commission for Maritime Services
\%http://www.rtcm.org/
.TP 3
2.\ here
\%http://gpsd.berlios.de/
