#!/bin/sh
#
# The regression-test driver script for the nmea2000 driver.
# CAN is a bit different from normal serial interfaces.
#

GPSD_PORT=2948
CAN_PLAYER=canplayer
TMP_PID_FILE=`mktemp`
TMP_OUT_FILE=`mktemp`
CAN_UNIT="vcan0"

# Requires GNU date extensions
# Should return an empty blank string if those are not present.
STARTTIME=`date +"%s" 2>/dev/null`

# We need to have the build directory in $GPSD_HOME to find the new gpsd
if [ "`dirname $0`" = "." ]; then
    GPSD_HOME=`pwd`
else
    GPSD_HOME=`dirname $0`
fi

version()
{
    echo `basename $0`" : Version v0.10";
}

usage()
{
    version; echo;
    echo "usage :" `basename $0` " [-S <portnumber>] [-u <can_device>] testfile";
    echo "      :" `basename $0` " -v";
    echo "      :" `basename $0` " -h";
}

while getopts :S:u:vh opt
do
    case ${opt} in
        S)  GPSD_PORT=${OPTARG};;
        u)  CAN_DEVICE=${OPTARG};;
        v)  version; exit 0;;
        h)  usage; exit 0;;
        \?) usage; exit 1;;
    esac
done

shift $((${OPTIND} - 1))

if [ -z $1 ]; then usage; exit 1; fi

TEST_FILE=$1


${GPSD_HOME}/gpsd -n -G -D0 -S ${GPSD_PORT} -P ${TMP_PID_FILE} nmea2000://${CAN_UNIT}

sleep 1

${GPSD_HOME}/gpspipe -d -r -w -S -o ${TMP_OUT_FILE} :${GPSD_PORT} 

sleep 1

${CAN_PLAYER} -I${TEST_FILE} ${CAN_UNIT}=can0

sleep 1

kill `cat ${TMP_PID_FILE}`

sleep 1

diff ${TEST_FILE}.chk ${TMP_OUT_FILE}

rm -f ${TMP_PID_FILE}
rm -f ${TMP_OUT_FILE}