#!/usr/bin/env python
#
# This is a valgrind torture test for the daemon.
#
import gpsfake 

debuglevel=1

invocation="valgrind --tool=memcheck --gen-suppressions=yes --leak-check=yes --suppressions=valgrind-suppressions"
test = gpsfake.TestSession(prefix=invocation, options="-D %d" % debuglevel)

try:
    print "\n*** Test #1: Normal single-session behavior."
    print "**** Add a GPS.\n"
    gps1 = test.gps_add("test/bu303-moving.log")

    print "\n**** Add and remove a client.\n"
    c1 = test.client_add("w\n")
    test.wait(3)
    test.client_remove(c1)

    print "\n**** Remove a GPS.\n"
    test.gps_remove(gps1)
    print "*** Test #1 complete."
finally:
    test.cleanup();
    test.killall()
