#!/bin/bash
#
# Upload git configuration from here to the repo
#
confdir=git.berlios.de:/gitroot/gpsd/

# Get around the ssh lockout on git.berlios.de by copying up to 
# shell.berlios.de and doing a local move. Written so the last
# move is atomic.
copy()
{
    scp $1 $LOGNAME@shell.berlios.de:STAGE
    ssh $LOGNAME@git.berlios.de "cp -f STAGE /gitroot/gpsd && mv /gitroot/gpsd/STAGE /gitroot/gpsd/$1"
}

if [ $1 ]
then
    for f in $*; do copy $f ; done
else
    copy config
    for file in hooks/*
    do
        copy $file
    done
fi

# End

