#!/bin/sh
#
# flockdriver - conduct regression tests as an argent for a remote flocktest
#
# usage: flockdriver -g gitname -m mailto
#
# The -g argument must be a git name valid for forming a clone URL
# The -m option must be a valid address for notification mail.
#
#  This will perform the following steps:
#
#  * If required, create the origin repo in a directory named after 
#     you beneath the test account home,
#
#   * git pull and build in that repo.
#
#   * make check, capturing the output
#
#   * mail the output back to you.
#
while getopts gm opt
do
    case $opt in
        g) gitname=$2; shift; shift ;;
	m) mailto=$2; shift; shift ;;
    esac
done

# Should yield a git URL valid for commit access
origin="ssh://${gitname}@git.berlios.de/gitroot/gpsd"

echo "site: `hostname --fqdn`" 
echo "mailto: $mailto"
echo "clone-url: $origin"

# End.
