#!/usr/bin/env python
#
# sizes -- explore the sizes of static gpsd binaries
#
import os

# NMEA variants other than vanilla NMEA
nmea_variants = [
  "--disable-fv18",
  "--disable-mtk3301",
  "--disable-tnt",
  "--disable-oceanserver",
  "--disable-gpsclock",
]

# Binary GPS protocols
binary_gps = [
  "--disable-oncore",
  "--disable-sirf",
  "--disable-superstar2",
  "--disable-tsip",
  "--disable-tripmate",
  "--disable-earthmate",
  "--disable-itrax",
  "--disable-ashtech",
  "--disable-navcom",
  "--disable-garmin",
  "--disable-garmintxt",
  "--disable-ubx",
  "--disable-geostar",
  "--disable-evermore",
]

# Differential correction and AIVDM
non_gps = [
  "--disable-rtcm104v2",
  "--disable-rtcm104v3",
  "--disable-ntrip",
  "--disable-aivdm",
  ]

# Time service
time_service = ["--disable-ntpshm", "--disable-pps"]

# Debugging and profiling
debugging = [
  "--disable-timing",
  "--disable-clientdebug",
  "--disable-oldstyle",
  ]

def sizeit(legend, tag, options):
    print legend + ":"
    print "Options:", " ".join(options)
    os.system("scons --disable-shared " + " ".join(options) + " >/dev/null")
    os.rename("gpsd", "gpsd-" + tag + "-build")

# Main sequence
os.system("uname -a")
sizeit("Minimalist build, stripped to NMEA only with shm interface",
       "minimalist",
       ["--disable-socket-export",
        "--disable-control-socket",
        "--disable-ipv6",
        "--enable-fixed-port-speed=9600",
        "--enable-max-devices=1",
        ] + nmea_variants+binary_gps+non_gps+time_service+debugging)
sizeit("Normal build, configure options defaulted", "normal", [])
os.system("size gpsd-*-build")
os.system("rm gpsd-*-build")

#end

