#!/usr/bin/python
#
# striplog -- strip leading lines from logs
#
# striplog -1 strips the first line only.
# striplog with no option strips all leading lines beginning with #
#
# This file is Copyright (c) 2010 by the GPSD project
# BSD terms apply: see the file COPYING in the distribution root for details.
#
import getopt, sys

secondline = firstline = False
stripval = 0
(options, arguments) = getopt.getopt(sys.argv[1:], "12n:")
for (switch, val) in options:
    if (switch == '-1'):
        firstline = True
    if (switch == '-2'):
        secondline = True
    if (switch == '-n'):
        stripval = int(val)

try:
    if firstline:
        sys.stdin.readline()
    elif secondline:
        sys.stdin.readline()
        sys.stdin.readline()
    elif stripval:
        for _dummy in range(stripval):
            sys.stdin.readline()
    else:
        while True:
            line = sys.stdin.readline()
            if line[0] != '#':
                break
        sys.stdout.write(line)

    sys.stdout.write(sys.stdin.read())
except KeyboardInterrupt:
    pass
