XML_SOURCES = explanation.xml \
	explan_bits.h.xml \
	explan_dgnss.c.xml \
	explan_dgpsip.c.xml \
	explan_drivers.c.xml \
	explan_geoid.c.xml \
	explan_gpsd.c.xml \
	explan_gpsd_dbus.c.xml \
	explan_gpsd.h.xml \
	explan_gps.h.xml \
	explan_gpsutils.c.xml \
	explan_isgps.c.xml \
	explan_libgps.c.xml \
	explan_libgpsd_core.c.xml \
	explan_libgpsmm.cpp.xml \
	explan_libgpsmm.h.xml \
	explan_netlib.c.xml \
	explan_nmea_parse.c.xml \
	explan_ntpshm.c.xml \
	explan_ntrip.c.xml \
	explan_packet.c.xml \
	explan_packet_names.h.xml \
	explan_packet_states.h.xml \
	explan_report.c.xml \
	explan_rtcm.c.xml \
	explan_serial.c.xml \
	explan_subframe.c.xml \
	explan_timebase.h.xml \
	explan_wrapup.xml

explanation.html: $(SOURCES)
	xmlto xhtml-nochunks explanation.xml
