#!/bin/bash
#
# Start Kismet, coping with the bad way it interacts with newer gpsd versions.
# Originally by Andreas Schneider <mail@cynapses.org>.  

# netcat runs 48 seconds
# gpsd should detect the baud rate in 40 sec
echo -e "p\nb\nb\nb\nb" | netcat -i 8 localhost 2947 >/dev/null 2>&1 &
sleep 40

kismet $*
