#!/bin/sh 
#
# Upload gpsd docs
#
webdir=shell.berlios.de:/home/groups/gpsd/htdocs
cgidir=shell.berlios.de:/home/groups/gpsd/cgi-bin

make html	# Ensure all derived HTML is up to date.

if [ $1 ]
then
    for f in $*; do scp $f $webdir/$f; done
else
    (cd performance; xmlto xhtml-nochunks performance.xml)
    scp start-kismet *.html *.png *.pdf *.gif *.css *.js *.txt \
	performance/{*.html,*.txt,*.png} \
	../TODO ../NEWS \
	$webdir
    scp gps_report.cgi $cgidir
fi

# To refresh the vendor-docs directory just do this:
# scp -r vendor-docs $webdir/vendor-docs
