#!/bin/sh 
#
# Upload gpsd docs
#
webdir=esr@shell.berlios.de:/home/groups/gpsd/htdocs
version=`sed <../Makefile -n -e '/^VERSION *= *\(.*\)/s//\1/p'`
echo "Uploading version $version"
sed -e "/@VERSION@/s//${version}/" -e "/@DATE@/s//`date '+%B %d, %Y'`/" <index.html.in >index.html
xmlto xhtml-nochunks ../gpsd.xml
xmlto xhtml-nochunks ../libgps.xml
xmlto xhtml-nochunks ../libgpsd.xml
xmlto xhtml-nochunks ../gpsprof.xml
xmlto xhtml-nochunks ../gpsfake.xml
xmlto xhtml-nochunks replacing-nmea.xml
(cd performance; xmlto xhtml-nochunks performance.xml)
# Doesn't upload PDFs or GIFs -- they aren't expected to change frequently
scp *.html performance/{*.html,*.txt,*.png} *.css *.js *.txt $webdir
